Producer:
    get:
        tags:
            - Producer
        summary: Get all producers
        security:
            - BearerAuth: []
        responses:
            200:
                description: List of producers
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: "../schemas/producer.yaml"
    post:
        tags:
            - Producer
        summary: Create producer
        security:
            - BearerAuth: []
        requestBody:
            content:
                application/json:
                    schema:
                        allOf:
                            - $ref: "../schemas/producer.yaml"
                            - $ref: "../schemas/required/producer.yaml"
                            - $ref: "../examples/producer.yaml"
        responses:
            201:
                $ref: "../responses/producer.yaml"
                description: Producer created

ProducerWithID:
    get:
        tags:
            - Producer
        summary: Get producer by ID
        security:
            - BearerAuth: []
        parameters:
            - in: path
              name: id
              required: true
              schema:
              type: string
              example: "1"
        responses:
            200:
                $ref: "../responses/producer.yaml"
                description: Producer found
    patch:
        tags:
            - Producer
        summary: Update producer
        security:
            - BearerAuth: []
        parameters:
            - in: path
              name: id
              required: true
              schema:
              type: string
              example: "1"
        requestBody:
            content:
                application/json:
                    schema:
                        allOf:
                            - $ref: "../schemas/producer.yaml"
                            - $ref: "../examples/producer.yaml"
        responses:
            201:
                $ref: "../responses/producer.yaml"
                description: Producer updated
    delete:
        tags:
            - Producer
        summary: Delete producer
        security:
            - BearerAuth: []
        parameters:
            - in: path
              name: id
              required: true
              schema:
              type: string
              example: "1"
        responses:
            204:
                description: Producer deleted
