framework:
    messenger:
        transports:
            async:
                dsn: '%env(RABBITMQ_URL)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

when@test:
   framework:
       messenger:
           transports:
               async: 'in-memory://'
