version: "3.9"

networks:
    stargaze-api:
        name: stargaze-api
        driver: bridge

services:
    nginx:
        container_name: nginx
        image: nginx:1.21.6-alpine
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/stargaze
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/php/php.ini:/etc/nginx/conf.d/php.ini
        networks:
            - stargaze-api
        depends_on:
            - php

    php:
        container_name: php
        image: php
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www/stargaze
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - stargaze-api
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres:14.2-alpine
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-stargaze-cinema}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
        networks:
            - stargaze-api
        volumes:
            - pg-storage:/var/lib/postgresql/data:rw

    minio:
        container_name: minio
        image: minio/minio:RELEASE.2022-04-26T01-20-24Z
        entrypoint: sh
        command: >
            -c 'mkdir -p /data/${MINIO_BUCKET:-stargazecinema} &&
            minio server --address 0.0.0.0:9000 --console-address ":9001" /data'
        ports:
            - 127.0.0.1:9000:9000
            - 9001:9001
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-mykey}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-mysecretkey}
        volumes:
            - minio-storage:/data
        healthcheck:
            test: [CMD, curl, -f, http://localhost:9000/minio/health/live]
            interval: 30s
            timeout: 20s
            retries: 3
        restart: on-failure
        networks:
            - stargaze-api

    mailhog:
        container_name: mailhog
        image: mailhog/mailhog:v1.0.1
        logging:
            driver: none
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - stargaze-api

    swagger-ui:
        container_name: swagger-ui
        image: swaggerapi/swagger-ui:v4.10.3
        ports:
            - 8080:8080
        volumes:
            - ./doc:/usr/share/nginx/html/doc
        environment:
            API_URL: doc/openapi.yaml
        networks:
            - stargaze-api
        depends_on:
            - nginx

volumes:
    minio-storage:
        name: minio-storage
        driver: local
    pg-storage:
        name: pg-storage
        driver: local
