version: "3.9"

networks:
    stargaze:
        driver: bridge

services:
    nginx:
        container_name: nginx
        image: nginx:1.21.6-alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/stargaze
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/php/php.ini:/etc/nginx/conf.d/php.ini
        networks:
            - stargaze
        depends_on:
            - php
            - postgres

    php:
        container_name: php
        image: php:8.1.3-fpm-alpine
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www/stargaze
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - stargaze
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres:14.2-alpine
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-stargaze-cinema}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
        networks:
            - stargaze
        volumes:
            - pg-storage:/var/lib/postgresql/data:rw

    minio:
        container_name: minio
        image: 'minio/minio:RELEASE.2022-03-14T18-25-24Z'
        command: server --address 0.0.0.0:9000 --console-address ":9001" /data
        ports:
            - "127.0.0.1:9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio-root-user}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio-root-password}
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-mykey}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-mysecretkey}
            MINIO_DEFAULT_BUCKETS: ${MINIO_BUCKET:-stargazecinema}
            MINIO_SITE_REGION: ${MINIO_REGION:-eu-central-1}
        volumes:
            - minio-storage:/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
        networks:
            - stargaze

    phppgadmin:
        container_name: phppgadmin
        image: neimheadh/phppgadmin:7.13.0
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
            POSTGRES_PASS: ${POSTGRES_PASSWORD:-secret}
        ports:
            - '8080:80'
        networks:
            - stargaze
        depends_on:
            - postgres

    swagger-ui:
        container_name: swagger-ui
        image: swaggerapi/swagger-ui:v4.6.2
        ports:
            - "8008:8080"
        volumes:
            - ./doc:/usr/share/nginx/html/doc
        environment:
            API_URL: doc/openapi.yaml
        networks:
            - stargaze
        depends_on:
            - nginx

volumes:
    minio-storage:
        driver: local
    pg-storage:
        driver: local
