version: "3.9"

services:
    nginx:
        container_name: nginx
        image: nginx:1.21.6-alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/stargaze
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/php/php.ini:/etc/nginx/conf.d/php.ini
        depends_on:
            - php
            - postgres

    php:
        container_name: php
        image: php:8.1.3-fpm-alpine
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www/stargaze
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres:14.2-alpine
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-stargaze-cinema}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
        volumes:
            - ./docker/database/data:/var/lib/postgresql/data:rw

    phppgadmin:
        container_name: phppgadmin
        image: neimheadh/phppgadmin:7.13.0
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=${POSTGRES_USER:-symfony}
            - POSTGRES_PASS=${POSTGRES_PASSWORD:-secret}
        ports:
            - '8080:80'
        depends_on:
            - postgres
