version: "3.8"

services:
  nginx-service:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/php/php.ini:/etc/nginx/conf.d/php.ini
    depends_on:
      - php-service
      - postgres-service

  php-service:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/project
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres-service

  postgres-service:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-stargaze-cinema}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data:rw
