parameters:
    locale: "en"
    cache_adapter: cache.adapter.apcu
    app.aws.s3.access_id: "%env(AWS_ACCESS_ID)%"
    app.aws.s3.access_secret: "%env(AWS_ACCESS_SECRET)%"
    app.aws.s3.bucket: "%env(AWS_BUCKET)%"
    app.aws.s3.region: "%env(AWS_REGION)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: "../src/"
        exclude:
            - ../src/DependencyInjection/
            - ../src/Entity/
            - ../src/Kernel.php

    App\Service\S3Service:
        arguments:
            - '@App\Factory\S3ClientFactory'
            - "%app.aws.s3.bucket%"

    App\Factory\S3ClientFactory:
        arguments:
            - "%app.aws.s3.region%"
            - "%app.aws.s3.access_id%"
            - "%app.aws.s3.access_secret%"
